spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website_log?useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /